name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
    - name: Build snapshot with GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: build --rm-dist --snapshot
    - name: Run Gosec Security Scanner
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...
    - name: Run Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.3"
        install-go: false
